config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users
  root to: 'posts#index'
  resources :posts, only: [:index, :show, :update, :zombie] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    # resources :recommendations, only: [:show]
    get 'total', to: 'posts#total'
    get 'zombie', to: 'posts#zombie'
    get 'murderer', to: 'posts#murderer'
    get 'thriller', to: 'posts#thriller'
    get 'monster', to: 'posts#monster'
    get 'occult', to: 'posts#occult'
    get 'japanese', to: 'posts#japanese'
    get 'grotesque', to: 'posts#grotesque'
    # get 'recommendations', to: 'posts#recommendations'
  end
  resources :recommendations, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content,      presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, through: :post_genres
  has_many :post_genres
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post, optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :images
  has_many :genres, through: :post_genres
  has_many :post_genres
  has_many :comments
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/post_genre.rb
class PostGenre < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :genre, optional: true
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  validates :content,      presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :recommendations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    @post = Post.find(params[:post_id])
    if @comment.save
      redirect_to post_path(@post)
      flash[:notice] = "🧟‍♀️コメント入力が完了しました🧟‍♂️"
    else
      redirect_to post_path(@post)
      flash[:notice] = "🧟‍♀️コメントが空欄です🧟‍♂️"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.includes(:images).order("likes_count DESC")
    @zombie = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 1}).order("likes_count DESC")
    @murderer = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 2}).order("likes_count DESC")
    @thriller = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 3}).order("likes_count DESC")
    @monster = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 4}).order("likes_count DESC")
    @occult = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 5}).order("likes_count DESC")
    @japanese = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 6}).order("likes_count DESC")
    @grotesque = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 7}).order("likes_count DESC")
    # @genre = Genre.all
  end

  def show
    @post = Post.find(params[:id])
    @images = @post.images
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def create
    Post.create(post_params)
  end

  def total
    @post = Post.includes(:images).order("likes_count DESC")
  end
  def zombie
    @post = Post.all
    @zombie = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 1}).order("likes_count DESC")
  end
  def murderer
    @post = Post.all
    @murderer = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 2}).order("likes_count DESC")
  end
  def thriller
    @post = Post.all
    @thriller = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 3}).order("likes_count DESC")
  end
  def monster
    @post = Post.all
    @monster = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 4}).order("likes_count DESC")
  end
  def occult
    @post = Post.all
    @occult = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 5}).order("likes_count DESC")
  end
  def japanese
    @post = Post.all
    @japanese = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 6}).order("likes_count DESC")
  end
  def grotesque
    @post = Post.all
    @grotesque = Post.joins(post_genres: :genre).includes(:images).where(genres: {id: 7}).order("likes_count DESC")
  end


  private
  def post_params
    params.require(:post).permit(:content).merge(user_id: current_user.id)
  end
  
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  def index
    @post = Post.all
    @recommend = Recommendation.new
  end

  def show
  end

  def create
    @comment = Comment.create(comment_params)
    @post = Post.find(params[:post_id])
    if @comment.save
      redirect_to post_path(@post)
      flash[:notice] = "🧟‍♀️コメント入力が完了しました🧟‍♂️"
    else
      redirect_to post_path(@post)
      flash[:notice] = "🧟‍♀️コメントが空欄です🧟‍♂️"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/layouts/_footer.html.haml
.footer

app/views/layouts/_header.html.haml
.header
  = link_to "血しぶきの館", root_path, class: "header__left--btn"
  .header__top
    - if user_signed_in?
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right"
    - else
      = link_to "ログイン", new_user_session_path, class: "header__right"
      = link_to "新規登録", new_user_registration_path, class: "header__right"
.header-second
  .header-second__total
    = link_to "総合ホラー", post_total_path(@post), class: "header__horror"
  .header-second__zombie
    = link_to "ゾンビ", post_zombie_path(@post), class: "header__horror"
  .header-second__murderer
    = link_to "サイコ", post_murderer_path(@post), class: "header__horror"
  .header-second__thriller
    = link_to "スリラー", post_thriller_path(@post), class: "header__horror"
  .header-second__monster
    = link_to "モンスター", post_monster_path(@post), class: "header__horror"
  .header-second__occult
    = link_to "オカルト", post_occult_path(@post), class: "header__horror"
  .header-second__japanese
    = link_to "Jホラー", post_japanese_path(@post), class: "header__horror"
  .header-second__grotesque
    = link_to "グロテスク", post_grotesque_path(@post), class: "header__horror"
  .header-second__recommend
    = link_to "みんなのおすすめ映画", recommendations_path, class: "header__horror"

app/views/layouts/_notifications.html.haml
.notification
 - if flash[:notice]
  %span= flash[:notice]
 - else flash[:notice]
  %span= flash[:notice]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HorrorReview
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    = javascript_include_tag 'application'
  %body
    = yield

app/views/likes/_like.html.haml
- if user_signed_in?
  - unless post.like_user(current_user.id).blank?
    = link_to post_like_path(post_id: post.id ,id: post.likes[0].id), method: :delete, remote: true do
      .vertical_like
        %i.material-icons.red-text お気に入りに追加しました 🧟‍♂️
        %span.red-text
        = post.likes_count
        -# .aaaaa
        -#   = post.likes_count
  - else
    = link_to post_likes_path(post.id), method: :post, remote: true do
      .vertical_like
        %i.material-icons.grey-text.text-darken-2 お気に入りに追加する 👨 
        %span.grey-text.text-darken-2
        = post.likes_count
        -# .aaaaa
        -#   = post.likes_count
-# - else
-#   - if post.likes_count > 0
-#     .vertical_like
-#       %i.material-icons.red-text お気に入り ♡
-#       %span.red-text
-#         = post.likes_count
-#   - else
-#     .vertical_like
-#       %i.material-icons.grey-text.text-darken-2 お気に入り ♡
-#       %span.grey-text.text-darken-2
-#         = post.likes_count

app/views/likes/create.html.haml
%h1 Likes#create
%p Find me in app/views/likes/create.html.haml

app/views/likes/create.js.erb
$(".vertical_like").html("<%= escape_javascript(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.html.haml
%h1 Likes#destroy
%p Find me in app/views/likes/destroy.html.haml

app/views/likes/destroy.js.erb
$(".vertical_like").html("<%= escape_javascript(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/grotesque.html.haml
= render 'layouts/header'
.detail-main
  .detail-main__total
    グロテスク映画ランキング
  .detail-main__content
    - @grotesque.each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .detail-main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .detail-main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/posts/index.html.haml
= render 'layouts/notifications'
= render 'layouts/header'
.main
  .main__total
    総合映画ランキング
  .main__content
    - @post.first(5).each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )
  .main__zombie
    ゾンビ映画ランキング
  .main__content
    - @zombie.first(5).each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )
  .main__murderer
    サイコ映画ランキング
  .main__content
    - @murderer.first(5).each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )
  .main__thriller
    スリラー映画ランキング
  .main__content
    - @thriller.first(5).each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )
  .main__monster
    モンスター映画ランキング
  .main__content
    - @monster.first(5).each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )
  .main__occult
    オカルト映画ランキング
  .main__content
    - @occult.first(5).each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )
  .main__japanese
    Jホラー映画ランキング
  .main__content
    - @japanese.first(5).each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )
  .main__grotesque
    グロテスク映画ランキング
  .main__content
    - @grotesque.first(5).each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/posts/japanese.html.haml
= render 'layouts/header'
.detail-main
  .detail-main__total
    Jホラー映画ランキング
  .detail-main__content
    - @japanese.each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .detail-main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .detail-main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/posts/monster.html.haml
= render 'layouts/header'
.detail-main
  .detail-main__total
    モンスター映画ランキング
  .detail-main__content
    - @monster.each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .detail-main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .detail-main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/posts/murderer.html.haml
= render 'layouts/header'
.detail-main
  .detail-main__total
    サイコ映画ランキング
  .detail-main__content
    - @murderer.each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .detail-main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .detail-main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/posts/occult.html.haml
= render 'layouts/header'
.detail-main
  .detail-main__total
    オカルト映画ランキング
  .detail-main__content
    - @occult.each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .detail-main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .detail-main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/posts/show.html.haml
= render 'layouts/notifications'
= render 'layouts/header'
.show
  .show__top-box
    .show__top-box__pic
      = image_tag @post.images[0][:pic], size: "346x560"
    .show__top-box__introduction
      .show__top-box__introduction__title
        = @post.title
        %span.show__top-box__introduction__title__date
          %br
          (
          = @post.year
          年制作の映画)
        .show__top-box__introduction__favourite
          お気に入り総数🧟‍♂️：
          = @post.likes_count
        .show__top-box__introduction__genre
          ジャンル：
          - @post.post_genres.each do |genre|
            ／
            = genre.genre.genre
        .show__top-box__introduction__country
          制作国：
          = @post.country
        .show__top-box__introduction__director
          監督：
          = @post.director
        .show__top-box__introduction__story
          あらすじ
        .show__top-box__introduction__story-detail
          = @post.story


  .show__comment
    .show__comment__field
      - if user_signed_in?
        = form_for [@post, @comment] do |f|
          = f.text_area :content, placeholder: "コメントする", class: 'comment-box'
          = f.submit "SEND", class: "form__submit"

          = render partial: 'likes/like', locals: { post: @post, likes: @likes}
      - else
        .show__comment__field__disabled-post
          コメントを投稿するには
          = link_to "ログイン", new_user_session_path, class: "log-in"
          、または
          = link_to "新規登録", new_user_registration_path, class: "log-in"
          をしてください。
          


    .show__comment__list
      .show__comment__list__display
        「
        = @post.title
        」
        %br
        に投稿された感想・評価（ネタバレあり）
      .show__comment__list__content
        - @comments.each do |comment|
          .show__comment__list__content__each
            「
            = comment.user.username
            」さんの感想・評価
            %span.show__comment__list__content__each__test
              = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
            %br
            = comment.content
  .show__footer
= render 'layouts/footer'

app/views/posts/thriller.html.haml
= render 'layouts/header'
.detail-main
  .detail-main__total
    スリラー映画ランキング
  .detail-main__content
    - @thriller.each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .detail-main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .detail-main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/posts/total.html.haml
= render 'layouts/header'
.detail-main
  .detail-main__total
    総合映画ランキング
  .detail-main__content
    - @post.each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .detail-main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .detail-main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/posts/zombie.html.haml
= render 'layouts/header'
.detail-main
  .detail-main__total
    ゾンビ映画ランキング
  .detail-main__content
    - @zombie.each.with_index(1) do |post, i|
      = link_to post_path(post.id) do
        .detail-main__content__each
          = i
          位👑
          = image_tag post.images[0][:pic], class: 'pic-size'
          = post.title.truncate(11)
          %br
          .detail-main__content__each__favourite
            お気に入り数
            (
            = post.likes_count
            )

app/views/recommendations/index.html.haml
= render 'layouts/header'
.recommendation-header
  .recommendation-header__top
    みんなのオススメホラー映画
.recommendation-heading
  .recommendation-heading__title
    日常に「ゾクゾク」をくれるホラー映画

.recommendation-comment
  - if user_signed_in?
    .recommendation-comment__content
      = form_for "aa" do |f|
        オススメしたい映画
        = f.text_field :content, placeholder: "タイトルを入力する", class: 'recommend-title-box'
        %br
        レビュー
        = f.text_area :content, placeholder: "コメントする", class: 'recommend-comment-box'
        = f.submit "SEND", class: "form__submit"

  - else
    .recommendation-comment__field__disabled-post
      コメントを投稿するには
      = link_to "ログイン", new_user_session_path, class: "log-in"
      、または
      = link_to "新規登録", new_user_registration_path, class: "log-in"
      をしてください。
          


-#     .recommendation__comment__list
-#       .recommendation__comment__list__display
-#         「
-#         = @post.title
-#         」
-#         %br
-#         に投稿された感想・評価（ネタバレあり）
-#       .recommendation__comment__list__content
-#         - @comments.each do |comment|
-#           .recommendation__comment__list__content__each
-#             「
-#             = comment.user.username
-#             」さんの感想・評価
-#             %span.show__comment__list__content__each__test
-#               = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
-#             %br
-#             = comment.content

app/views/recommendations/show.html.haml
-# .recommendation__comment
-#   .recommendation__comment__field
-#     - if user_signed_in?
-#       = form_for "a" do |f|
-#         = f.text_area :content, placeholder: "コメントする", class: 'comment-box'
-#         = f.submit "SEND", class: "form__submit"

-#         = render partial: 'likes/like', locals: { post: @post, likes: @likes}
-#     - else
-#       .recommendation__comment__field__disabled-post
-#         コメントを投稿するには
-#         = link_to "ログイン", new_user_session_path, class: "log-in"
-#         、または
-#         = link_to "新規登録", new_user_registration_path, class: "log-in"
-#         をしてください。
          


-#     .recommendation__comment__list
-#       .recommendation__comment__list__display
-#         「
-#         = @post.title
-#         」
-#         %br
-#         に投稿された感想・評価（ネタバレあり）
-#       .recommendation__comment__list__content
-#         - @comments.each do |comment|
-#           .recommendation__comment__list__content__each
-#             「
-#             = comment.user.username
-#             」さんの感想・評価
-#             %span.show__comment__list__content__each__test
-#               = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
-#             %br
-#             = comment.content